#sudo: required
#dist: trusty
language: node_js
node_js:
  - "6.1"

install:
#  - sudo apt-get update
#  - sudo apt-get install -y nodejs
  - npm install -g reveal-md@0.1.1

script:
  - chmod +x fix.sh
  - ./fix.sh
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master