#sudo: required
#dist: trusty
language: node_js
node_js:
  - "6.1"

install:
#  - sudo apt-get update
#  - sudo apt-get install -y nodejs
  - npm install -g reveal-md@0.1.1

script:
  - for f in *.md; do echo $f; reveal-md $f --static ${f%.*}; done
  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master