#sudo: required
#dist: trusty
language: node_js
node_js:
  - "6.1"

install:
#  - sudo apt-get update
#  - sudo apt-get install -y nodejs
  - npm install -g reveal-md@0.1.1

script:
  - for f in *.md; do echo $f; reveal-md $f --static ${f%.*};  done
  - for f in *.md; do echo $f; sed -e "s#href=\"/css#href=\"/presentations/${f%.*}/css#g" -i ${f%.*}/index.html; done
  - for f in *.md; do echo $f; sed -e "s#src=\"/lib#src=\"/presentations/${f%.*}/lib#g" -i ${f%.*}/index.html; done
  - for f in *.md; do echo $f; sed -e "s#src=\"/js#src=\"/presentations/${f%.*}/js#g" -i ${f%.*}/index.html; done
  - for f in *.md; do echo $f; sed -e "s#src: \'/lib#src: \'/presentations/${f%.*}/lib#g" -i ${f%.*}/index.html; done
  - for f in *.md; do echo $f; sed -e "s#src: \'/plugin#src: \'/presentations/${f%.*}/plugin#g" -i ${f%.*}/index.html; done
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master